### PR TITLE
Don't store files from the build process

### PR DESCRIPTION
**Pull request by rillig**
Files that are created during the build process should not be stored in
the repository, since they differ for each platform and can easily be
reconstructed anyway.

### CODE REVIEW

**Comment by rillig** [comment]
This change not only reduces the amount of checked-out files, it also removes the symlinks from openssl/man/man3, which are difficult to handle on Windows platforms.

**Comment by LBiv** [comment]
OK, will add this.

**Comment by LBiv** [comment]
Wait, if I do this, I don't think providers/build.sh will run

**Comment by LBiv** [comment]
Wait, nevermind you're right the archives contains the libraries. Thank you!

**Pull request closed without merging**
